sudo: required
services:
  - docker

before_install:
  - docker build -t havan7135/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true havan7135/react-docker npm run test -- --coverage

deploy:
  provider: heroku
  api_key:
    secure: "$API_KEY"
  app: react-docker-demo
  on: master
