version: "3"
services:
  react-docker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # Do not try to map a folder against /app/node_modules inside the container
      - .:/app
