version: "3"
services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    # Fix react-scripts error
    stdin_open: true
    # Code below fix not auto reloading after a code change
    environment:
      - CHOKIDAR_USEPOLLING=true
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    # override a command
    command: ["yarn", "test"]
    # Fix react-scripts error
    stdin_open: true
    # Code below fix not auto reloading after a code change
    environment:
      - CHOKIDAR_USEPOLLING=true
